name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.42.4

      - name: Build CLI tool
        run: |
          deno compile --allow-read --allow-write --output=csvgen_for_windows.exe --target=x86_64-pc-windows-msvc ./src/cli.ts
          deno compile --allow-read --allow-write --output=csvgen_for_linux --target=x86_64-unknown-linux-gnu ./src/cli.ts
          deno compile --allow-read --allow-write --output=csvgen_for_mac_x86_64 --target=x86_64-apple-darwin ./src/cli.ts
          deno compile --allow-read --allow-write --output=csvgen_for_mac_arm --target=aarch64-apple-darwin ./src/cli.ts

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./csvgen_for_windows.exe
            ./csvgen_for_linux
            ./csvgen_for_mac_x86_64
            ./csvgen_for_mac_arm
