name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.42.3

      - name: test
        run: ls -la

      - name: Build CLI tool for Windows
        run: deno compile --allow-read --allow-write --output=csvgen-for-windows.exe --target=x86_64-pc-windows-msvc ./cli.ts

      - name: Build CLI tool for Linux
        run: deno compile --allow-read --allow-write --output=csvgen-for-linux --target=x86_64-unknown-linux-gnu ./cli.ts

      - name: Buld CLI tool for Mac(x86_64)
        run: deno compile --allow-read --allow-write --output=csvgen-for-mac-with-x86_64 --target=x86_64-apple-darwin ./cli.ts

      - name: Buld CLI tool for Mac(ARM)
        run: deno compile --allow-read --allow-write --output=csvgen-for-mac-with-arm --target=aarch64-apple-darwin ./cli.ts

      - name: test
        run: ls -la

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            "csvgen-for-windows.exe"
            "csvgen-for-linux"
            "csvgen-for-mac-with-x86_64"
            "csvgen-for-mac-with-arm"
