name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.42.4

      - name: Set up variables
        run: |
          export WINDOWS_FILE=csvgen_for_windows.exe
          export LINUX_FILE=csvgen_for_linux
          export MAC_X86_64_FILE=csvgen_for_mac_x86_64
          export MAC_ARM_FILE=csvgen_for_mac_arm

      - name: Build CLI tool
        run: |
          deno compile --allow-read --allow-write --output=$WINDOWS_FILE --target=x86_64-pc-windows-msvc ./cli.ts
          deno compile --allow-read --allow-write --output=$LINUX_FILE --target=x86_64-unknown-linux-gnu ./cli.ts
          deno compile --allow-read --allow-write --output=$MAC_X86_64_FILE --target=x86_64-apple-darwin ./cli.ts
          deno compile --allow-read --allow-write --output=$MAC_ARM_FILE --target=aarch64-apple-darwin ./cli.ts

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./$WINDOWS_FILE
            ./$LINUX_FILE
            ./$MAC_X86_64_FILE
            ./$MAC_ARM_FILE
